[ req ]
default_bits       = 2048
distinguished_name = req_distinguished_name
prompt             = no

[ req_distinguished_name ]
C  = IN
ST = Maharashtra
L  = Thane
O  = Sales Department, litware
CN = sales.litware.com
emailAddress = sales@litware.com
